project:
  type: website
  output-dir: docs


website:
  title: "Angelo Santos"
  favicon: /images/favicon.ico
  navbar:
    logo: /images/favicon-32x32.png
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: work.qmd
        text: Working Experience
      - href: teaching.qmd
        text: Teaching
      - href: coding.qmd
        text: Coding
      - href: me.qmd
        text: Personal


    right: 
      - icon: envelope-fill
        href: mailto:angelofgdsantos@gmail.com
      - icon: github
        href: https://github.com/angelofgdsantos
      - icon: linkedin
        href: https://www.linkedin.com/in/angelo-santos-2854bb147/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false






