baseURL: "https://angelofgdsantos.github.io/" 
title: Angelo Santos 
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Working experience
          url: working_experience/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        - name: About me
          url: personal/
          weight: 4

        # - name: Courses
        #   url: courses/
        #   weight: 2
        # - name: Data
        #   url: data/
        #   weight: 3 
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: ""
    author: Angelo Santos
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Angelo Santos
          subtitle: "Hello! I am a PhD candidate at the University of Houston. I am specializing in applied microeconomics, 
          focused on development and environmental economics. My research addresses critical issues such as deforestation 
          and air pollution, aiming to develop effective policies to mitigate these challenges. I am also a nature enthusiast 
          and soccer lover.<br><br>

          You can find my CV [**here**](angelo_santos_cv.pdf)"


          imageUrl: "profile_square.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Angelo Santos
          buttons:
            # - name: Papers
            #   url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
            # - name: Tags
              # url: tags/
            # - name: Archive
            #   url: archive/
            - name: Research
              url: research/
            - name: Working experience
              url: working_experience/
            - name: Teaching
              url: teaching/
            - name: About me
              url: personal/


    socialIcons:
        # - name: CV
        #   url: angelo_santos_cv.pdf
        - name: Email
          url: mailto:afdossan@cougarnet.uh.edu
        - name: Linkedin
          url: https://www.linkedin.com/in/angelo-santos-2854bb147/
        # - name: Office Hours
        #   url: officehours/
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/angelofgdsantos
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: Twitter
        #   url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Angelo Santos"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
