---
title: ""
---

### University of Pennsylvania - Population Studies Center

* Postdoctoral Fellow - 2025 - 2027 

### University of Houston - NSF Funded Project 

* Doctoral researcher for the PIRE project - 2023 - 2025 

    * [Title: “Climate risk, pollution, and childhood inequalities in
    low- and middle-income countries”](https://ceci.sas.upenn.edu)
    * Partners: World Bank, IDB, ADB, UNICEF, Regional Institute for Population Studies in Ghana, University of Pennsylvania and the University of Houston
    * Award Number: 2230615

* RA for [Chinhui Juhn](https://uh.edu/%7Ecjuhn/) and [Yona Rubinstein](https://www.lse.ac.uk/management/people/academic-staff/yona-rubinstein) - 2021 - 2023

### Inter-American Development Bank, USA.

* Winter intern as Data Anlyst at the Education Division - 2024

###  Young Lives, University of Oxford, UK.

* Data Matching event - 2024

### Federal University of Pernambuco (UFPE), Brazil.

* Graduate RA for [FACEPE](https://www.facepe.br) - 2018 - 2020
* Graduate RA at Nucleo de Estudos Regionais e Urbanos (NERU) - 2018 - 2020
* Undergraduate RA at [PET-Economia](https://sites.ufpe.br/peteconomia/) - 2014 - 2017



